version: 0.2
phases:
  install:
    commands:
      - echo "Install phase"
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo "Build phase"
      - cp -r * /usr/share/nginx/html
      - cp -r * /var/www/html
  post_build:
    commands:
      - echo "Configuring Nginx"
      - sudo systemctl start nginx
      - sudo systemctl enable nginx
      - sudo systemctl status nginx

artifacts:
  files:
    - '**/*'

